### PR TITLE
Added possibility to create session Cookie

### PR DESCRIPTION
**Pull request by MaybachDomei**
Added sessionOnly paramter.
By Default it is set to false.

### CODE REVIEW

**Comment by arlogilbert** [comment]
@MaybachDomei what is the purpose of the session only cookie?

**Comment by MaybachDomei** [comment]
The cookie popup is session based. So every new Session the cookie popup shows again.
The law says every new session you have to accept the cookies again. (In EU)

**Comment by ghost** [comment]
@arlogilbert can you merge this pull request please? In Austria / EU this law has high priority.
Thank you!

**Comment by hodonsky** [comment]
@MaybachDomei I assume the problem is compliance, not extension of this plugin.

The documentation tells us how to use the `expiryDays` option in the config to take this same effect and you can see it on line 50: `(expiryDays || 365)`

This way if you use `0` or `false` or `undefined` or `null` when setting that property it will set it for 1 year. However, if you set it to -1, it will actually use that value, and set it behind a day, making it already expire meeting the requirements of the compliance laws.

https://cookieconsent.osano.com/documentation/javascript-api/

It's about two page scrolls down or you can ctrl+f/cmd+f for `cookie.expiryDays`

Please let me know if this resolves your issue.

**Pull request closed without merging**
