### PR TITLE
[FIX] fix breaking dismissOnClick

### PR DESCRIPTION
**Pull request by SlootSantos**
- change event.path to event.composedPath
- bc event.path is non-standard

### CODE REVIEW

**Comment by kai-mattern** [comment]
Can we get any update if this PR is going to be integrated?

**Comment by vlrprbttst** [comment]
@Robertof76 how to i integrate this in my existing code? I get an error
`Uncaught SyntaxError: Unexpected end of input`

**Comment by SlootSantos** [comment]
We actually monkey patch this library.
We did so in extending the prototyp with the "composedPath" functionality if not available natively.

**Comment by hodonsky** [comment]
I'm closing this because this fix is already in another PR that already made it into dev. It will be in the next release of v3.X.Y

**Pull request closed without merging**
