### PR TITLE
Code fix to allow changing of cookie values

### PR DESCRIPTION
**Pull request by dweuthen**
Changing the static configuration of cookieconsent.status is being ignored under certain circumstances. This code change fixes this issue.

### CODE REVIEW

**Comment by cf-nsousa** [comment]
We just had the same problem, while trying to define our own values.
These changes match with our own fix. Please, accept this ;)

**Comment by ErinPo** [comment]
Hm, how do you change the static configuration though? 

I tried changing the defaults using:

`window.cookieconsent.initialise({
  "cookieconsent": {
    "status": {
      "deny": false,
      "allow": true,
      "dismiss": null
    }
  }, // etc.`

But this fails even with your fix...

**Comment by dweuthen** [comment]
In my case I've implemented it like this:

```
window.addEventListener("load", function(){
  window.cookieconsent.hasTransition = false;
  window.cookieconsent.status = {deny: 'deny-20180831', allow: 'allow-20180831', dismiss: 'dismiss-20180831'};
  
  window.cookieconsent.initialise({
    "cookie": {
      "domain": ".example.com",
      "expiryDays": 30,
      "secure": true
    },
  })
});
```

**Comment by ErinPo** [comment]
Awesome, that did it for me as well - thanks! I suppose you are adding the date of the user action to schedule when to show the banner again the next time? Couldn't this just be handled with the expiryDays variable?

**Comment by dweuthen** [comment]
No, the timestamp in the value of the cookie, helps me to have all visitors see the banner again, once the linked policies have been updated. 
EXAMPLE: If I update policies today, I change the timestamp in the cookieconsent properties, which means that all existing cookies are no longer valid, and the banner is shown again. I did not want to nag visitors if nothing has changed, that's why expiryDays wasn't my preferred method.

**Comment by ErinPo** [comment]
I see, so that date is the version date of your consent statement, not the date of consent. That is so clever for handling policy changes!

Yeah, your expiry date is even very short at 30 days. Afaik, it is only recommended to renew consent after one year (even if the policy has not changed). Not sure how soon we may ask users again who have dismissed the banner without consenting.

**Comment by hodonsky** [comment]
@dweuthen What's your use case for needing to modify these? If I'm not mistaken these are just internal values only ever exposed in the `onStatusChange` callback. And being that they're really meant to be constants and just a value for reference in a call back I'm not sure what value would be in changing them or having them be customizable because they will always represent the same thing.

**Comment by dweuthen** [comment]
@relicmelex I described the use case in one of my previous comments:

> EXAMPLE: If I update policies today, I change the timestamp in the cookieconsent properties, which means that all existing cookies are no longer valid, and the banner is shown again. I did not want to nag visitors if nothing has changed, that's why expiryDays wasn't my preferred method.

In a nutshell: I want to show the consent to visitors again, if the polices were updated and only then.

Since the API documentation says those values are configurable, the code should check the configurable values. That's what my code change does.

**Comment by hodonsky** [comment]
Ahh, okay thank you for clearing that up. So what you're talking about is a new feature and should be implemented, but not in this way.

I solute you for making something possible where it wasn't previously with this clever fix... However; Unfortunately what you've created here is a hack and not a long term solution.

What we will probably end up doing to solve this is give a policy ID as part of the configuration, so if that changes it will allow a new hook to trigger a reinitialization based on the return value or a callback. This will end up in multiple places in the future as well for redundancy.

Also thank you for your note about the documentation, we will have to adjust that to reflect the current state of the project.

For now you have two options, neither of which are great:

First - Set your package.json to point to your fork until we add this feature ( coming soon, I just haven't set a priority for the new features yet as we're still taking care of some small bugs other are experiencing ), which isn't hard to do, just annoying because you have to keep checking for updates, and you can't use our CDN. Like I said, not great.

Second - Set another cookie with your policyId, ( this falls within the 'necessary to make the app function' category of legal cookies ) and use the current hooks to check that policyId against the new one. This would be what I would do, and is probably close to how the new feature will work when we implement it.

Again, I want to thank you for this PR but unfortunately I have to close it without accepting. Now, if you'd like to give another go at the solution in that manner, in CookieConsent with another PR, I'd be happy to look at it and add that feature the second way. To extend that thought if you do decide to take this on, don't just go about extending the current cookie, each should have a specific responsibility to its value and purpose. This prevents later having integration issues or breaking changes on other new feature adds.

Cheers!

**Pull request closed without merging**
