### PR TITLE
fix: Keyboard users can now interact with the buttons

### PR DESCRIPTION
**Pull request by robbiepaul**
Having the elements `a[role=button]` is ok, however omitting the href attribute makes it impossible to interact with the element with a keyboard.

We could add a href with something like `javascript:void(0)` however this isn't semantically correct. We should instead use the button element which doesn't require the href attribute to interact with it.

Because we're now using the button element we can drop the `role=button` as the role is implicit.

### CODE REVIEW

**Comment by robbiepaul** [comment]
Any update with this? I'm sure keyboard users would appreciate this being looked at.

**Comment by edoorn** [comment]
Very interested in seeing this update. +1

**Comment by ErinPo** [comment]
Two of those links actually have href values and so need not be changed to buttons in order to become keyboard navigable. In fact, switching them to buttons breaks the intended appearance for those links.

**Comment by robbiepaul** [comment]
@ErinPo Yep you're right. That's why I've left the two links with hrefs as anchor tags (I just removed their `role=button` since they're actually links

**Comment by masi** [comment]
Any updates on this issue? The fact that you cannot interact with the button with a keyboard makes it impossible to use when you want/need to comply with accessibility laws in any countries.

**Pull request closed without merging**
