### PR TITLE
fix(iphone): dismissOnWindowClick

### LINKED ISSUE #529: iPhone: Safari: dismissOnWindowClick not working properly due to 'click' event
IOS Version 12.1.4

closing consent with click out (actually touch out) does not work when cookie consent is displayed on iPhone Safari and dismissOnWindowClick is enabled

### PR DESCRIPTION
**Pull request by halafi**
Fixes #529

### CODE REVIEW

**Comment by thexmanxyz** [comment]
@halafi  A bit more explanation on what the fix exactly does would be useful. But even though +1

**Comment by halafi** [comment]
the `onClick` event does not fire on mobile safari, `onTouchEnd` works

**Comment by thexmanxyz** [comment]
@halafi that is obvious ;). the question is at what action or point it does not fire. because what I see it is within the autoDismiss logic.

**Comment by halafi** [comment]
closing with click out (actually touch out) does not work when cookie consent is displayed on iPhone Safari and `dismissOnWindowClick` is enabled

**Comment by thexmanxyz** [comment]
@halafi thx for clarification, I don't want to bug you. But I just wanted to understand what it exactly does and it is probably also useful for others.

**Pull request merged**
